# Generated by Django 5.0.6 on 2024-06-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NHLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('conference', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('team_logo', models.ImageField(upload_to='logos/nhl')),
            ],
            options={
                'verbose_name': 'NHL Team',
                'verbose_name_plural': 'NHL Teams',
            },
        ),
        migrations.CreateModel(
            name='NHLStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('games_played', models.IntegerField()),
                ('num_of_overtime_losses', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('points_percentage', models.FloatField()),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('wins_of_regulation', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhl.nhlteam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NHLGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_pts', models.IntegerField(blank=True, null=True)),
                ('home_pts', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True)),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('waiting', 'Waiting')], max_length=10)),
                ('arena', models.CharField(blank=True, max_length=100)),
                ('overtime', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='nhl.nhlteam')),
                ('visitor_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_games', to='nhl.nhlteam')),
            ],
            options={
                'verbose_name': 'NHL Game',
                'verbose_name_plural': 'NHL Games',
            },
        ),
    ]
