# Generated by Django 5.0.6 on 2024-05-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhlteam',
            name='team_logo',
            field=models.ImageField(default=1, upload_to='logos/nhl'),
            preserve_default=False,
        ),
    ]
