# Generated by Django 5.0.6 on 2024-06-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlgame',
            name='time',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
