# Generated by Django 5.0.6 on 2024-06-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0002_nhlteam_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhlgame',
            name='overtime',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='nhlgame',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
