# Generated by Django 5.0.6 on 2024-06-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0002_alter_nhlgame_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlgame',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
