# Generated by Django 5.0.6 on 2024-06-21 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0003_alter_nhlgame_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NHLTeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('penalties_in_minutes', models.IntegerField(blank=True, null=True)),
                ('even_strength_goals', models.IntegerField(blank=True, null=True)),
                ('shots_on_goal', models.IntegerField(blank=True, null=True)),
                ('shooting_percentage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='nhlgame',
            name='box_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NHLBoxScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_stats', to='nhl.nhlteamstats')),
                ('visitor_team_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_team_stats', to='nhl.nhlteamstats')),
            ],
        ),
    ]
