# Generated by Django 5.0.6 on 2024-06-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0003_nhlgame_overtime_nhlgame_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlgame',
            name='home_pts',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='nhlgame',
            name='visitor_pts',
            field=models.CharField(max_length=10),
        ),
    ]
