# Generated by Django 5.0.6 on 2024-06-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0004_nhlteamstats_nhlgame_box_score_nhlboxscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhlteamstats',
            name='power_play_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nhlteamstats',
            name='short_handed_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
