# Generated by Django 5.0.6 on 2024-06-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0004_alter_nhlgame_home_pts_alter_nhlgame_visitor_pts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlgame',
            name='overtime',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
