# Generated by Django 5.0.6 on 2024-06-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0005_alter_nhlgame_overtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhlgame',
            name='box_score_link',
        ),
    ]
