# Generated by Django 5.0.6 on 2024-06-21 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0005_nhlteamstats_power_play_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlgame',
            name='box_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhl.nhlboxscore'),
        ),
    ]
