# Generated by Django 5.0.6 on 2024-06-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0006_remove_nhlgame_box_score_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlgame',
            name='home_pts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nhlgame',
            name='visitor_pts',
            field=models.IntegerField(),
        ),
    ]
