# Generated by Django 5.0.6 on 2024-05-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fav_league',
            field=models.ManyToManyField(blank=True, to='core.league'),
        ),
    ]
