# Generated by Django 5.0.6 on 2024-05-28 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0002_customuser_fav_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Team',
                'verbose_name_plural': 'Favorite Teams',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_teams',
            field=models.ManyToManyField(blank=True, related_name='favorite_teams', through='users.FavoriteTeam', to='contenttypes.contenttype'),
        ),
    ]
