# Generated by Django 5.0.6 on 2024-06-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0003_favoriteteam_customuser_favorite_teams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteTeam',
            new_name='Favorite',
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fav_league',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_teams',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
