version: '3'

services:
  web:
    build: .
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn leagueverse.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: league_verse
      POSTGRES_USER: vlone
      POSTGRES_PASSWORD: pass

  redis:
    image: redis:6
    ports:
      - "6381:6379"

  celery:
    build: .
    command: celery -A leagueverse worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A leagueverse beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
