# Generated by Django 5.0.6 on 2024-07-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscription'),
        ('users', '0004_telegramuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='TelegramSubscription',
        ),
        migrations.AlterField(
            model_name='telegramsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser'),
        ),
    ]
