# Generated by Django 5.0.6 on 2024-05-22 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBATeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('conference', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'NBA Team',
                'verbose_name_plural': 'NBA Teams',
            },
        ),
        migrations.CreateModel(
            name='NBAStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('winning_percentage', models.FloatField()),
                ('games_back', models.CharField(max_length=10)),
                ('points_percentage_game', models.FloatField()),
                ('oop_points_percentage_game', models.FloatField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.nbateam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NBAGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_pts', models.IntegerField()),
                ('home_pts', models.IntegerField()),
                ('date', models.DateField()),
                ('box_score_link', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('waiting', 'Waiting')], max_length=10)),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='nba.nbateam')),
                ('visitor_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_games', to='nba.nbateam')),
            ],
            options={
                'verbose_name': 'NBA Game',
                'verbose_name_plural': 'NBA Games',
            },
        ),
    ]
