# Generated by Django 5.0.6 on 2024-06-09 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBABoxScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NBATeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('conference', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('team_logo', models.ImageField(upload_to='logos/nba')),
            ],
            options={
                'verbose_name': 'NBA Team',
                'verbose_name_plural': 'NBA Teams',
            },
        ),
        migrations.CreateModel(
            name='NBATeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_goals', models.IntegerField(default=0)),
                ('field_goal_attempts', models.IntegerField(default=0)),
                ('three_point_field_goals', models.IntegerField(default=0)),
                ('three_point_field_goal_attempts', models.IntegerField(default=0)),
                ('free_throws', models.IntegerField(default=0)),
                ('free_throw_attempts', models.IntegerField(default=0)),
                ('personal_fouls', models.IntegerField(default=0)),
                ('total_rebounds', models.IntegerField(default=0)),
                ('offensive_rebounds', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NBAStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('winning_percentage', models.FloatField()),
                ('games_back', models.CharField(max_length=10)),
                ('points_percentage_game', models.FloatField()),
                ('oop_points_percentage_game', models.FloatField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.nbateam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NBAGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_pts', models.CharField(max_length=10)),
                ('home_pts', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('box_score_link', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('waiting', 'Waiting')], max_length=10)),
                ('box_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_games', to='nba.nbaboxscore')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='nba.nbateam')),
                ('visitor_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_games', to='nba.nbateam')),
            ],
            options={
                'verbose_name': 'NBA Game',
                'verbose_name_plural': 'NBA Games',
            },
        ),
        migrations.AddField(
            model_name='nbaboxscore',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_box_scores', to='nba.nbateam'),
        ),
        migrations.AddField(
            model_name='nbaboxscore',
            name='visitor_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_box_scores', to='nba.nbateam'),
        ),
        migrations.AddField(
            model_name='nbaboxscore',
            name='home_stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_stats', to='nba.nbateamstats'),
        ),
        migrations.AddField(
            model_name='nbaboxscore',
            name='visitor_stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_stats', to='nba.nbateamstats'),
        ),
    ]
