# Generated by Django 5.0.6 on 2024-05-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbagame',
            name='home_pts',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='nbagame',
            name='visitor_pts',
            field=models.CharField(max_length=10),
        ),
    ]
