# Generated by Django 5.0.6 on 2024-06-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_alter_nbagame_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbagame',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
