# Generated by Django 5.0.6 on 2024-06-14 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_alter_nbagame_home_pts_alter_nbagame_visitor_pts'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBATeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_goals', models.IntegerField(default=0)),
                ('field_goal_attempts', models.IntegerField(default=0)),
                ('field_goals_percentage', models.FloatField(default=0.0)),
                ('three_point_field_goals', models.IntegerField(default=0)),
                ('three_point_field_goal_attempts', models.IntegerField(default=0)),
                ('three_point_field_goals_percentage', models.FloatField(default=0.0)),
                ('free_throws', models.IntegerField(default=0)),
                ('free_throw_attempts', models.IntegerField(default=0)),
                ('free_throw_percentage', models.FloatField(default=0.0)),
                ('personal_fouls', models.IntegerField(default=0)),
                ('total_rebounds', models.IntegerField(default=0)),
                ('offensive_rebounds', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='nbagame',
            name='box_score_link',
        ),
        migrations.AddField(
            model_name='nbateam',
            name='team_logo',
            field=models.ImageField(default=1, upload_to='logos/nba'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NBABoxScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nba.nbagame')),
                ('home_team_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_box_scores', to='nba.nbateamstats')),
                ('visitor_team_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_box_scores', to='nba.nbateamstats')),
            ],
        ),
    ]
