# Generated by Django 5.0.6 on 2024-06-14 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0003_nbateamstats_remove_nbagame_box_score_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbaboxscore',
            name='game',
        ),
        migrations.AddField(
            model_name='nbagame',
            name='box_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nba.nbaboxscore'),
        ),
        migrations.AlterField(
            model_name='nbaboxscore',
            name='home_team_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_stats', to='nba.nbateamstats'),
        ),
        migrations.AlterField(
            model_name='nbaboxscore',
            name='visitor_team_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_team_stats', to='nba.nbateamstats'),
        ),
        migrations.AlterField(
            model_name='nbagame',
            name='home_pts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nbagame',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='nba.nbateam'),
        ),
        migrations.AlterField(
            model_name='nbagame',
            name='visitor_pts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nbagame',
            name='visitor_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_team', to='nba.nbateam'),
        ),
    ]
