# Generated by Django 5.0.6 on 2024-06-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0003_nbagame_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbateam',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/nba'),
        ),
    ]
