# Generated by Django 5.0.6 on 2024-06-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0004_remove_nbaboxscore_game_nbagame_box_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbagame',
            name='home_pts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nbagame',
            name='visitor_pts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
