# Generated by Django 5.0.6 on 2024-05-14 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('sport', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
            },
        ),
        migrations.CreateModel(
            name='NBATeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('conference', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'NBA Team',
                'verbose_name_plural': 'NBA Teams',
            },
        ),
        migrations.CreateModel(
            name='NHLTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('conference', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'NHL Team',
                'verbose_name_plural': 'NHL Teams',
            },
        ),
        migrations.CreateModel(
            name='NBAStandings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0, verbose_name='Wins')),
                ('losses', models.IntegerField(default=0, verbose_name='Losses')),
                ('home_record', models.CharField(max_length=10, verbose_name='Home Record')),
                ('away_record', models.CharField(max_length=10, verbose_name='Away Record')),
                ('last_ten_games', models.CharField(max_length=10, verbose_name='Last 10 Games')),
                ('streak', models.CharField(max_length=10, verbose_name='Current Streak')),
                ('winning_percentage', models.FloatField(verbose_name='Winning Percentage')),
                ('games_back', models.FloatField(verbose_name='Games Back')),
                ('points_percentage_game', models.FloatField(verbose_name='Points Percentage Game')),
                ('oop_points_percentage_game', models.FloatField(verbose_name='Opponent Points Percentage Game')),
                ('conference_record', models.CharField(verbose_name='Conference Record')),
                ('division_record', models.CharField(verbose_name='Division Record')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.nbateams')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NHLStandings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0, verbose_name='Wins')),
                ('losses', models.IntegerField(default=0, verbose_name='Losses')),
                ('home_record', models.CharField(max_length=10, verbose_name='Home Record')),
                ('away_record', models.CharField(max_length=10, verbose_name='Away Record')),
                ('last_ten_games', models.CharField(max_length=10, verbose_name='Last 10 Games')),
                ('streak', models.CharField(max_length=10, verbose_name='Current Streak')),
                ('num_of_overtime_losses', models.IntegerField(verbose_name='Number of Overtime Losses')),
                ('num_of_regulation_and_overtime_wins', models.IntegerField(verbose_name='Number of Regulation and Overtime Wins')),
                ('shootout_wins', models.IntegerField(verbose_name='Shootout Wins')),
                ('shootout_losses', models.IntegerField(verbose_name='Shootout Losses')),
                ('goals_for', models.IntegerField(verbose_name='Goals For')),
                ('goals_against', models.IntegerField(verbose_name='Goals Against')),
                ('goal_differential', models.IntegerField(verbose_name='Goal Differential')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.nhlteams')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
