# Generated by Django 5.0.6 on 2024-05-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbateams',
            name='conference',
            field=models.CharField(choices=[('Eastern', 'Eastern'), ('Western', 'Western')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nhlteams',
            name='conference',
            field=models.CharField(choices=[('Eastern', 'Eastern'), ('Western', 'Western')], max_length=10),
        ),
    ]
