# Generated by Django 5.0.6 on 2024-05-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_alter_nbastandings_away_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbastandings',
            name='away_record',
        ),
        migrations.RemoveField(
            model_name='nbastandings',
            name='conference_record',
        ),
        migrations.RemoveField(
            model_name='nbastandings',
            name='division_record',
        ),
        migrations.RemoveField(
            model_name='nbastandings',
            name='home_record',
        ),
        migrations.RemoveField(
            model_name='nbastandings',
            name='last_ten_games',
        ),
        migrations.RemoveField(
            model_name='nbastandings',
            name='streak',
        ),
        migrations.RemoveField(
            model_name='nhlstandings',
            name='away_record',
        ),
        migrations.RemoveField(
            model_name='nhlstandings',
            name='home_record',
        ),
        migrations.RemoveField(
            model_name='nhlstandings',
            name='last_ten_games',
        ),
        migrations.RemoveField(
            model_name='nhlstandings',
            name='streak',
        ),
    ]
